imports: []
resources:
- name: dhatu-compute-template
  properties:
    name: dhatu-compute-template
    properties:
      disks:
      - autoDelete: true
        boot: true
        initializeParams:
          sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
      machineType: n1-standard-4
      metadata:
        items:
        - key: startup-script
          value: '#!/bin/bash

            apt-get update

            apt-get install -y docker.io python3 python3-pip

            systemctl start docker

            systemctl enable docker

            usermod -aG docker $USER

            '
      networkInterfaces:
      - accessConfigs:
        - name: External NAT
          type: ONE_TO_ONE_NAT
        network: global/networks/default
      tags:
        items:
        - dhatu-compute
  type: compute.v1.instanceTemplate
- name: dhatu-health-check
  properties:
    checkIntervalSec: 30
    healthyThreshold: 2
    httpHealthCheck:
      port: 8080
      requestPath: /health
    timeoutSec: 10
    type: HTTP
    unhealthyThreshold: 3
  type: compute.v1.healthCheck
- name: dhatu-compute-group
  properties:
    autoHealingPolicies:
    - healthCheck: $(ref.dhatu-health-check.selfLink)
      initialDelaySec: 300
    baseInstanceName: dhatu-compute
    instanceTemplate: $(ref.dhatu-compute-template.selfLink)
    targetSize: 4
    zone: us-central1-a
  type: compute.v1.instanceGroupManager
- name: dhatu-autoscaler
  properties:
    autoscalingPolicy:
      coolDownPeriodSec: 300
      cpuUtilization:
        utilizationTarget: 0.7
      maxNumReplicas: 25
      minNumReplicas: 2
    target: $(ref.dhatu-compute-group.selfLink)
    zone: us-central1-a
  type: compute.v1.autoscaler
