apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dhatu-cpu-compute
  name: dhatu-cpu-compute
  namespace: dhatu-processing
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dhatu-cpu-compute
  template:
    metadata:
      labels:
        app: dhatu-cpu-compute
    spec:
      containers:
      - env:
        - name: NODE_TYPE
          value: cpu_compute
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              key: batch_size
              name: dhatu-config
        image: dhatu-processing:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        name: dhatu-processor
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
