apiVersion: v1
kind: Service
metadata:
  name: dhatu-processing-service
  namespace: dhatu-processing
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dhatu-cpu-compute
  type: LoadBalancer
